# snakemake -s mr.smk --configfile config0.yaml -j 4 --keep-going
# snakejob -s mr.smk --configfile config0.yaml -j 1000 --max-jobs-per-second 1 --keep-going
# snakejob -s mr.smk --configfile config0.yaml -j 500 --max-jobs-per-second 1 --keep-going --until manhattan_plot

DataOut: "data/MR_ADphenome/"
DataOutput: "results/MR_ADphenome/"

REF: 'raw/EUR_All_Chr'
clumpr2: 0.001 ## Default in TwoSample MR
clumpkb: 10000 ## 10 MB, default in TwoSampleMR
Pthreshold: ['5e-8', '5e-6']

# Forbidden wildcard combinations
## Blacklist alcohol consumption onto Kunkle 2019 (LOAD) and Hilbar 2017 (HV) in line with data use aggreements
## Blacklist all other phenotypes onto Lambert 2013 (LOAD) and Hilbar 2015 (HV)
missing: [
   {"ExposureCode" : "Liu2019smkcpd23andMe", "OutcomeCode" : "Lambert2013load", "Pthreshold" : "5e-8"},
   {"ExposureCode" : "Liu2019smkcpd23andMe", "OutcomeCode" : "Lambert2013load", "Pthreshold" : "5e-6"},
   {"ExposureCode" : "Liu2019smkcpd23andMe", "OutcomeCode" : "Hilbar2015hipv", "Pthreshold" : "5e-8"},
   {"ExposureCode" : "Liu2019smkcpd23andMe", "OutcomeCode" : "Hilbar2015hipv", "Pthreshold" : "5e-6"}
]



EXPOSURES:
  -
    CODE: Liu2019smkcpd23andMe
    NAME: 'Smoking Quantity'
    FILE: raw/GWAS/Liu2019smkcpd23andMe.chrall.CPRA_b37.tsv.gz
    COLUMNS:
      SNP: DBSNP_ID
      CHROM: CHROM
      POS: POS
      REF: REF
      ALT: ALT
      AF: AF
      BETA: BETA
      SE: SE
      P: P
      Z: Z
      N: N
      TRAIT: TRAIT


OUTCOMES:
  -
    CODE: Lambert2013load
    NAME: LOAD
    FILE: raw/GWAS/Lambert2013load.chrall.CPRA_b37.tsv.gz
    COLUMNS:
      SNP: DBSNP_ID
      CHROM: CHROM
      POS: POS
      REF: REF
      ALT: ALT
      AF: AF
      BETA: BETA
      SE: SE
      P: P
      Z: Z
      N: N
      TRAIT: TRAIT
  -
    CODE: Kunkle2019load
    NAME: LOAD
    FILE: raw/GWAS/Kunkle2019load.chrall.CPRA_b37.tsv.gz
    COLUMNS:
      SNP: DBSNP_ID
      CHROM: CHROM
      POS: POS
      REF: REF
      ALT: ALT
      AF: AF
      BETA: BETA
      SE: SE
      P: P
      Z: Z
      N: N
      TRAIT: TRAIT
  -
    CODE: Huang2017aaos
    NAME: AAOS
    FILE: raw/GWAS/Huang2017aaos.chrall.CPRA_b37.tsv.gz
    COLUMNS:
      SNP: DBSNP_ID
      CHROM: CHROM
      POS: POS
      REF: REF
      ALT: ALT
      AF: AF
      BETA: BETA
      SE: SE
      P: P
      Z: Z
      N: N
      TRAIT: TRAIT
  -
    CODE: Deming2017ab42
    NAME: 'CSF Ab42'
    FILE: raw/GWAS/Deming2017ab42.chrall.CPRA_b37.tsv.gz
    COLUMNS:
      SNP: DBSNP_ID
      CHROM: CHROM
      POS: POS
      REF: REF
      ALT: ALT
      AF: AF
      BETA: BETA
      SE: SE
      P: P
      Z: Z
      N: N
      TRAIT: TRAIT
  -
    CODE: Deming2017ptau
    NAME: 'CSF Ptau'
    FILE: raw/GWAS/Deming2017ptau.chrall.CPRA_b37.tsv.gz
    COLUMNS:
      SNP: DBSNP_ID
      CHROM: CHROM
      POS: POS
      REF: REF
      ALT: ALT
      AF: AF
      BETA: BETA
      SE: SE
      P: P
      Z: Z
      N: N
      TRAIT: TRAIT
  -
    CODE: Deming2017tau
    NAME: 'CSF Tau'
    FILE: raw/GWAS/Deming2017tau.chrall.CPRA_b37.tsv.gz
    COLUMNS:
      SNP: DBSNP_ID
      CHROM: CHROM
      POS: POS
      REF: REF
      ALT: ALT
      AF: AF
      BETA: BETA
      SE: SE
      P: P
      Z: Z
      N: N
      TRAIT: TRAIT
  -
    CODE: Hilbar2017hipv
    NAME: 'Hippocampal Volume'
    FILE: raw/GWAS/Hilbar2017hipv.chrall.CPRA_b37.tsv.gz
    COLUMNS:
      SNP: DBSNP_ID
      CHROM: CHROM
      POS: POS
      REF: REF
      ALT: ALT
      AF: AF
      BETA: BETA
      SE: SE
      P: P
      Z: Z
      N: N
      TRAIT: TRAIT
  -
    CODE: Hilbar2015hipv
    NAME: 'Hippocampal Volume'
    FILE: raw/GWAS/Hilbar2015hipv.chrall.CPRA_b37.tsv.gz
    COLUMNS:
      SNP: DBSNP_ID
      CHROM: CHROM
      POS: POS
      REF: REF
      ALT: ALT
      AF: AF
      BETA: BETA
      SE: SE
      P: P
      Z: Z
      N: N
      TRAIT: TRAIT
  -
    CODE: Beecham2014npany
    NAME: 'Any Neuritic Plaques'
    FILE: raw/GWAS/Beecham2014npany.chrall.CPRA_b37.tsv.gz
    COLUMNS:
      SNP: DBSNP_ID
      CHROM: CHROM
      POS: POS
      REF: REF
      ALT: ALT
      AF: AF
      BETA: BETA
      SE: SE
      P: P
      Z: Z
      N: N
      TRAIT: TRAIT
  -
    CODE: Beecham2014braak4
    NAME: 'Neurofibrillary Tangles'
    FILE: raw/GWAS/Beecham2014braak4.chrall.CPRA_b37.tsv.gz
    COLUMNS:
      SNP: DBSNP_ID
      CHROM: CHROM
      POS: POS
      REF: REF
      ALT: ALT
      AF: AF
      BETA: BETA
      SE: SE
      P: P
      Z: Z
      N: N
      TRAIT: TRAIT
  -
    CODE: Beecham2014vbiany
    NAME: 'Vascular Brain Injury'
    FILE: raw/GWAS/Beecham2014vbiany.chrall.CPRA_b37.tsv.gz
    COLUMNS:
      SNP: DBSNP_ID
      CHROM: CHROM
      POS: POS
      REF: REF
      ALT: ALT
      AF: AF
      BETA: BETA
      SE: SE
      P: P
      Z: Z
      N: N
      TRAIT: TRAIT
  -
    CODE: Beecham2014status
    NAME: 'Neuropathologic AD'
    FILE: raw/GWAS/Beecham2014status.chrall.CPRA_b37.tsv.gz
    COLUMNS:
      SNP: DBSNP_ID
      CHROM: CHROM
      POS: POS
      REF: REF
      ALT: ALT
      AF: AF
      BETA: BETA
      SE: SE
      P: P
      Z: Z
      N: N
      TRAIT: TRAIT
