# snakemake -s mr.smk --configfile config/config.yaml -j 4 --keep-going
# snakejob -s mr.smk --configfile config/config.yaml -j 1000 --max-jobs-per-second 1 --keep-going --notemp

PROJECT: "test"
RLIB: "renv/library/R-3.6/x86_64-pc-linux-gnu"

REF: 'raw/EUR_All_Chr'
clumpr2: 0.001 ## Default in TwoSample MR
clumpkb: 10000 ## 10 MB, default in TwoSampleMR
Pthreshold: ['5e-8', '5e-6']

EXCLUSION:
  -
    NAME: NULL
    NOTE: NULL
    CHROM: NULL
    START: NULL
    STOP: NULL


# Forbidden wildcard combinations
## Blacklist alcohol consumption onto Kunkle 2019 (LOAD) and Hilbar 2017 (HV) in line with data use aggreements
## Blacklist all other phenotypes onto Lambert 2013 (LOAD) and Hilbar 2015 (HV)
missing: [
   {"Project" : "test", "ExposureCode" : "Willer2013ldl", "OutcomeCode" : "Lambert2013load", "Pthreshold" : "5e-8"},
   ]



EXPOSURES:
  -
    CODE: Willer2013ldl
    NAME: 'LDL cholesterol'
    FILE: data/raw/GWAS/Willer2013ldl.chrall.CPRA_b37.tsv.gz
    COLUMNS:
      SNP: DBSNP_ID
      CHROM: CHROM
      POS: POS
      REF: REF
      ALT: ALT
      AF: AF
      BETA: BETA
      SE: SE
      P: P
      Z: Z
      N: N
      TRAIT: TRAIT

OUTCOMES:
  -
    CODE: Lambert2013load
    NAME: LOAD
    FILE: data/raw/GWAS/Lambert2013load.chrall.CPRA_b37.tsv.gz
    COLUMNS:
      SNP: DBSNP_ID
      CHROM: CHROM
      POS: POS
      REF: REF
      ALT: ALT
      AF: AF
      BETA: BETA
      SE: SE
      P: P
      Z: Z
      N: N
      TRAIT: TRAIT
  -
    CODE: Kunkle2019load
    NAME: LOAD
    FILE: data/raw/GWAS/Kunkle2019load.chrall.CPRA_b37.tsv.gz
    COLUMNS:
      SNP: DBSNP_ID
      CHROM: CHROM
      POS: POS
      REF: REF
      ALT: ALT
      AF: AF
      BETA: BETA
      SE: SE
      P: P
      Z: Z
      N: N
      TRAIT: TRAIT
